include(${top}/set.cmake)
macro(check_rv)
	if (${ARGV0})
		message(FATAL_ERROR "test failed")
	endif()
endmacro()

execute_process( COMMAND ${doxygen} Doxyfile RESULT_VARIABLE rv)
check_rv(${rv})

foreach (_check IN LISTS check)
	set(xml_file "out_${_check}")
	message(STATUS "LINT xml/${_check} > ${xml_file}")
	execute_process( COMMAND xmllint --format --noblanks --nowarning xml/${_check} --output ${xml_file} RESULT_VARIABLE rv)
	#	check_rv(${rv})
	message(STATUS "CHOMP VOLATILE")
	file(READ ${xml_file} OUT_XML)
	STRING(REGEX REPLACE "version=\"${doxygen_version_major}.${doxygen_version_minor}.${doxygen_version_revision}\"" "version=\"\"" OUT_WO_VERSION_XML "${OUT_XML}")
	file(WRITE ${xml_file} ${OUT_WO_VERSION_XML})
	message(STATUS "DIFF ${xml_file} ${dirname}/${_check}")
	execute_process( COMMAND diff -u ${xml_file} ${dirname}/${_check} RESULT_VARIABLE rv)
	check_rv(${rv})
endforeach()
